# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CVQTui.ui'
#
# Created: Mon Jul  6 01:04:14 2015
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1283, 752)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 169, 169))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 169, 169))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 169, 169))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frame)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.rbActiveImg = QtGui.QRadioButton(self.frame)
        self.rbActiveImg.setAutoExclusive(False)
        self.rbActiveImg.setObjectName(_fromUtf8("rbActiveImg"))
        self.gridLayout_9.addWidget(self.rbActiveImg, 1, 1, 1, 1)
        self.rbOrigImg = QtGui.QRadioButton(self.frame)
        self.rbOrigImg.setAutoExclusive(False)
        self.rbOrigImg.setObjectName(_fromUtf8("rbOrigImg"))
        self.gridLayout_9.addWidget(self.rbOrigImg, 1, 0, 1, 1)
        self.stackedWidget_2 = QtGui.QStackedWidget(self.frame)
        self.stackedWidget_2.setObjectName(_fromUtf8("stackedWidget_2"))
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.page_7)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblActiveImage = QtGui.QLabel(self.page_7)
        self.lblActiveImage.setMinimumSize(QtCore.QSize(400, 300))
        self.lblActiveImage.setObjectName(_fromUtf8("lblActiveImage"))
        self.horizontalLayout.addWidget(self.lblActiveImage)
        self.stackedWidget_2.addWidget(self.page_7)
        self.page_8 = QtGui.QWidget()
        self.page_8.setObjectName(_fromUtf8("page_8"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page_8)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_2 = QtGui.QLabel(self.page_8)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_7.addWidget(self.label_2)
        self.stackedWidget_2.addWidget(self.page_8)
        self.gridLayout_9.addWidget(self.stackedWidget_2, 0, 1, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(self.frame)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.page)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblOriginalImage = QtGui.QLabel(self.page)
        self.lblOriginalImage.setMinimumSize(QtCore.QSize(400, 300))
        self.lblOriginalImage.setAutoFillBackground(False)
        self.lblOriginalImage.setObjectName(_fromUtf8("lblOriginalImage"))
        self.horizontalLayout_2.addWidget(self.lblOriginalImage)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label = QtGui.QLabel(self.page_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_6.addWidget(self.label)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_9.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.GreyscaleTab = QtGui.QWidget()
        self.GreyscaleTab.setObjectName(_fromUtf8("GreyscaleTab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.GreyscaleTab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 3, 1, 1)
        self.tabWidget.addTab(self.GreyscaleTab, _fromUtf8(""))
        self.tabColorOps = QtGui.QWidget()
        self.tabColorOps.setObjectName(_fromUtf8("tabColorOps"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabColorOps)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.tabColorOps)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lblLH = QtGui.QLabel(self.groupBox_2)
        self.lblLH.setObjectName(_fromUtf8("lblLH"))
        self.gridLayout_8.addWidget(self.lblLH, 0, 1, 1, 1)
        self.cbColorMask = QtGui.QComboBox(self.groupBox_2)
        self.cbColorMask.setObjectName(_fromUtf8("cbColorMask"))
        self.cbColorMask.addItem(_fromUtf8(""))
        self.cbColorMask.addItem(_fromUtf8(""))
        self.cbColorMask.addItem(_fromUtf8(""))
        self.cbColorMask.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.cbColorMask, 1, 0, 1, 1)
        self.lblCmask1_1 = QtGui.QLabel(self.groupBox_2)
        self.lblCmask1_1.setObjectName(_fromUtf8("lblCmask1_1"))
        self.gridLayout_8.addWidget(self.lblCmask1_1, 0, 2, 1, 1)
        self.lblUV = QtGui.QLabel(self.groupBox_2)
        self.lblUV.setObjectName(_fromUtf8("lblUV"))
        self.gridLayout_8.addWidget(self.lblUV, 2, 4, 1, 1)
        self.rbColorMask = QtGui.QRadioButton(self.groupBox_2)
        self.rbColorMask.setObjectName(_fromUtf8("rbColorMask"))
        self.gridLayout_8.addWidget(self.rbColorMask, 0, 7, 1, 1)
        self.lblUS = QtGui.QLabel(self.groupBox_2)
        self.lblUS.setObjectName(_fromUtf8("lblUS"))
        self.gridLayout_8.addWidget(self.lblUS, 1, 4, 1, 1)
        self.lblCmask2_1 = QtGui.QLabel(self.groupBox_2)
        self.lblCmask2_1.setObjectName(_fromUtf8("lblCmask2_1"))
        self.gridLayout_8.addWidget(self.lblCmask2_1, 1, 2, 1, 1)
        self.sbUS = QtGui.QSpinBox(self.groupBox_2)
        self.sbUS.setMaximum(255)
        self.sbUS.setProperty("value", 255)
        self.sbUS.setObjectName(_fromUtf8("sbUS"))
        self.gridLayout_8.addWidget(self.sbUS, 1, 6, 1, 1)
        self.lblLV = QtGui.QLabel(self.groupBox_2)
        self.lblLV.setObjectName(_fromUtf8("lblLV"))
        self.gridLayout_8.addWidget(self.lblLV, 2, 1, 1, 1)
        self.sbUV = QtGui.QSpinBox(self.groupBox_2)
        self.sbUV.setMaximum(255)
        self.sbUV.setProperty("value", 255)
        self.sbUV.setObjectName(_fromUtf8("sbUV"))
        self.gridLayout_8.addWidget(self.sbUV, 2, 6, 1, 1)
        self.lblLS = QtGui.QLabel(self.groupBox_2)
        self.lblLS.setObjectName(_fromUtf8("lblLS"))
        self.gridLayout_8.addWidget(self.lblLS, 1, 1, 1, 1)
        self.sbLV = QtGui.QSpinBox(self.groupBox_2)
        self.sbLV.setMaximum(255)
        self.sbLV.setObjectName(_fromUtf8("sbLV"))
        self.gridLayout_8.addWidget(self.sbLV, 2, 3, 1, 1)
        self.sbUH = QtGui.QSpinBox(self.groupBox_2)
        self.sbUH.setMaximum(255)
        self.sbUH.setProperty("value", 255)
        self.sbUH.setObjectName(_fromUtf8("sbUH"))
        self.gridLayout_8.addWidget(self.sbUH, 0, 6, 1, 1)
        self.sbLH = QtGui.QSpinBox(self.groupBox_2)
        self.sbLH.setMaximum(255)
        self.sbLH.setObjectName(_fromUtf8("sbLH"))
        self.gridLayout_8.addWidget(self.sbLH, 0, 3, 1, 1)
        self.lblUH = QtGui.QLabel(self.groupBox_2)
        self.lblUH.setObjectName(_fromUtf8("lblUH"))
        self.gridLayout_8.addWidget(self.lblUH, 0, 4, 1, 1)
        self.sbLS = QtGui.QSpinBox(self.groupBox_2)
        self.sbLS.setMaximum(255)
        self.sbLS.setObjectName(_fromUtf8("sbLS"))
        self.gridLayout_8.addWidget(self.sbLS, 1, 3, 1, 1)
        self.lblCmask3_1 = QtGui.QLabel(self.groupBox_2)
        self.lblCmask3_1.setObjectName(_fromUtf8("lblCmask3_1"))
        self.gridLayout_8.addWidget(self.lblCmask3_1, 2, 2, 1, 1)
        self.lblCmask1_2 = QtGui.QLabel(self.groupBox_2)
        self.lblCmask1_2.setObjectName(_fromUtf8("lblCmask1_2"))
        self.gridLayout_8.addWidget(self.lblCmask1_2, 0, 5, 1, 1)
        self.lblCmask2_2 = QtGui.QLabel(self.groupBox_2)
        self.lblCmask2_2.setObjectName(_fromUtf8("lblCmask2_2"))
        self.gridLayout_8.addWidget(self.lblCmask2_2, 1, 5, 1, 1)
        self.lblCmask3_2 = QtGui.QLabel(self.groupBox_2)
        self.lblCmask3_2.setObjectName(_fromUtf8("lblCmask3_2"))
        self.gridLayout_8.addWidget(self.lblCmask3_2, 2, 5, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 7, 2, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 10, 2, 1)
        self.groupBox = QtGui.QGroupBox(self.tabColorOps)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.listGreyscale = QtGui.QListWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listGreyscale.sizePolicy().hasHeightForWidth())
        self.listGreyscale.setSizePolicy(sizePolicy)
        self.listGreyscale.setMaximumSize(QtCore.QSize(150, 125))
        self.listGreyscale.setFrameShape(QtGui.QFrame.StyledPanel)
        self.listGreyscale.setObjectName(_fromUtf8("listGreyscale"))
        item = QtGui.QListWidgetItem()
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        font = QtGui.QFont()
        font.setKerning(True)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listGreyscale.addItem(item)
        self.gridLayout_7.addWidget(self.listGreyscale, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 8, 2, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tabColorOps, _fromUtf8(""))
        self.tabGreyscaleOps = QtGui.QWidget()
        self.tabGreyscaleOps.setObjectName(_fromUtf8("tabGreyscaleOps"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tabGreyscaleOps)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem2, 0, 3, 1, 1)
        self.gbHistograms = QtGui.QGroupBox(self.tabGreyscaleOps)
        self.gbHistograms.setObjectName(_fromUtf8("gbHistograms"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.gbHistograms)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.btnEqualizeHist = QtGui.QPushButton(self.gbHistograms)
        self.btnEqualizeHist.setObjectName(_fromUtf8("btnEqualizeHist"))
        self.verticalLayout_12.addWidget(self.btnEqualizeHist)
        self.btnCLAHE = QtGui.QPushButton(self.gbHistograms)
        self.btnCLAHE.setObjectName(_fromUtf8("btnCLAHE"))
        self.verticalLayout_12.addWidget(self.btnCLAHE)
        self.gridLayout_10.addWidget(self.gbHistograms, 0, 0, 1, 1)
        self.gbSmoothing = QtGui.QGroupBox(self.tabGreyscaleOps)
        self.gbSmoothing.setObjectName(_fromUtf8("gbSmoothing"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.gbSmoothing)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.btnBlurAveraging = QtGui.QPushButton(self.gbSmoothing)
        self.btnBlurAveraging.setObjectName(_fromUtf8("btnBlurAveraging"))
        self.verticalLayout_13.addWidget(self.btnBlurAveraging)
        self.btnBlurGaussian = QtGui.QPushButton(self.gbSmoothing)
        self.btnBlurGaussian.setObjectName(_fromUtf8("btnBlurGaussian"))
        self.verticalLayout_13.addWidget(self.btnBlurGaussian)
        self.btnBlurMedian = QtGui.QPushButton(self.gbSmoothing)
        self.btnBlurMedian.setObjectName(_fromUtf8("btnBlurMedian"))
        self.verticalLayout_13.addWidget(self.btnBlurMedian)
        self.btnFilterBilateral = QtGui.QPushButton(self.gbSmoothing)
        self.btnFilterBilateral.setObjectName(_fromUtf8("btnFilterBilateral"))
        self.verticalLayout_13.addWidget(self.btnFilterBilateral)
        self.gridLayout_10.addWidget(self.gbSmoothing, 0, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tabGreyscaleOps)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_14 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.btnThreshGlobal = QtGui.QPushButton(self.groupBox_3)
        self.btnThreshGlobal.setObjectName(_fromUtf8("btnThreshGlobal"))
        self.gridLayout_14.addWidget(self.btnThreshGlobal, 0, 0, 1, 1)
        self.btnThreshMean = QtGui.QPushButton(self.groupBox_3)
        self.btnThreshMean.setObjectName(_fromUtf8("btnThreshMean"))
        self.gridLayout_14.addWidget(self.btnThreshMean, 2, 0, 1, 1)
        self.btnThreshGaussian = QtGui.QPushButton(self.groupBox_3)
        self.btnThreshGaussian.setObjectName(_fromUtf8("btnThreshGaussian"))
        self.gridLayout_14.addWidget(self.btnThreshGaussian, 3, 0, 1, 1)
        self.cbThreshType = QtGui.QComboBox(self.groupBox_3)
        self.cbThreshType.setObjectName(_fromUtf8("cbThreshType"))
        self.cbThreshType.addItem(_fromUtf8(""))
        self.cbThreshType.addItem(_fromUtf8(""))
        self.cbThreshType.addItem(_fromUtf8(""))
        self.cbThreshType.addItem(_fromUtf8(""))
        self.cbThreshType.addItem(_fromUtf8(""))
        self.gridLayout_14.addWidget(self.cbThreshType, 0, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lblThreshThresh = QtGui.QLabel(self.groupBox_3)
        self.lblThreshThresh.setObjectName(_fromUtf8("lblThreshThresh"))
        self.horizontalLayout_4.addWidget(self.lblThreshThresh)
        self.sbThreshThresh = QtGui.QSpinBox(self.groupBox_3)
        self.sbThreshThresh.setFrame(False)
        self.sbThreshThresh.setMaximum(255)
        self.sbThreshThresh.setProperty("value", 127)
        self.sbThreshThresh.setObjectName(_fromUtf8("sbThreshThresh"))
        self.horizontalLayout_4.addWidget(self.sbThreshThresh)
        self.gridLayout_14.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lblThreshMaxval = QtGui.QLabel(self.groupBox_3)
        self.lblThreshMaxval.setObjectName(_fromUtf8("lblThreshMaxval"))
        self.horizontalLayout_5.addWidget(self.lblThreshMaxval)
        self.sbThreshMaxval = QtGui.QSpinBox(self.groupBox_3)
        self.sbThreshMaxval.setFrame(False)
        self.sbThreshMaxval.setMaximum(255)
        self.sbThreshMaxval.setProperty("value", 255)
        self.sbThreshMaxval.setObjectName(_fromUtf8("sbThreshMaxval"))
        self.horizontalLayout_5.addWidget(self.sbThreshMaxval)
        self.gridLayout_14.addLayout(self.horizontalLayout_5, 3, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_3, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tabGreyscaleOps, _fromUtf8(""))
        self.tabBinaryOps = QtGui.QWidget()
        self.tabBinaryOps.setObjectName(_fromUtf8("tabBinaryOps"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabBinaryOps)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 2, 1, 1)
        self.gbMorphology = QtGui.QGroupBox(self.tabBinaryOps)
        self.gbMorphology.setObjectName(_fromUtf8("gbMorphology"))
        self.gridLayout_11 = QtGui.QGridLayout(self.gbMorphology)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.btnDilate = QtGui.QPushButton(self.gbMorphology)
        self.btnDilate.setObjectName(_fromUtf8("btnDilate"))
        self.gridLayout_11.addWidget(self.btnDilate, 0, 3, 1, 1)
        self.btnClose = QtGui.QPushButton(self.gbMorphology)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.gridLayout_11.addWidget(self.btnClose, 1, 3, 1, 1)
        self.btnOpen = QtGui.QPushButton(self.gbMorphology)
        self.btnOpen.setObjectName(_fromUtf8("btnOpen"))
        self.gridLayout_11.addWidget(self.btnOpen, 1, 1, 1, 1)
        self.btnMorphGradient = QtGui.QPushButton(self.gbMorphology)
        self.btnMorphGradient.setObjectName(_fromUtf8("btnMorphGradient"))
        self.gridLayout_11.addWidget(self.btnMorphGradient, 2, 1, 1, 1)
        self.btnBlackHat = QtGui.QPushButton(self.gbMorphology)
        self.btnBlackHat.setObjectName(_fromUtf8("btnBlackHat"))
        self.gridLayout_11.addWidget(self.btnBlackHat, 3, 3, 1, 1)
        self.btnTopHat = QtGui.QPushButton(self.gbMorphology)
        self.btnTopHat.setObjectName(_fromUtf8("btnTopHat"))
        self.gridLayout_11.addWidget(self.btnTopHat, 2, 3, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_7 = QtGui.QLabel(self.gbMorphology)
        self.label_7.setMinimumSize(QtCore.QSize(40, 0))
        self.label_7.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.sbKernel1 = QtGui.QSpinBox(self.gbMorphology)
        self.sbKernel1.setMinimumSize(QtCore.QSize(45, 30))
        self.sbKernel1.setMaximumSize(QtCore.QSize(45, 30))
        self.sbKernel1.setMinimum(1)
        self.sbKernel1.setMaximum(20)
        self.sbKernel1.setProperty("value", 5)
        self.sbKernel1.setObjectName(_fromUtf8("sbKernel1"))
        self.horizontalLayout_3.addWidget(self.sbKernel1)
        self.label_5 = QtGui.QLabel(self.gbMorphology)
        self.label_5.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.sbKernel2 = QtGui.QSpinBox(self.gbMorphology)
        self.sbKernel2.setMinimumSize(QtCore.QSize(45, 30))
        self.sbKernel2.setMaximumSize(QtCore.QSize(45, 30))
        self.sbKernel2.setMinimum(1)
        self.sbKernel2.setMaximum(20)
        self.sbKernel2.setProperty("value", 5)
        self.sbKernel2.setObjectName(_fromUtf8("sbKernel2"))
        self.horizontalLayout_3.addWidget(self.sbKernel2)
        self.gridLayout_11.addLayout(self.horizontalLayout_3, 0, 0, 4, 1)
        self.btnErode = QtGui.QPushButton(self.gbMorphology)
        self.btnErode.setStyleSheet(_fromUtf8(""))
        self.btnErode.setObjectName(_fromUtf8("btnErode"))
        self.gridLayout_11.addWidget(self.btnErode, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.gbMorphology, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabBinaryOps, _fromUtf8(""))
        self.FindContoursTab = QtGui.QWidget()
        self.FindContoursTab.setObjectName(_fromUtf8("FindContoursTab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.FindContoursTab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 1, 3, 1, 1)
        self.gbEdges = QtGui.QGroupBox(self.FindContoursTab)
        self.gbEdges.setObjectName(_fromUtf8("gbEdges"))
        self.gridLayout_12 = QtGui.QGridLayout(self.gbEdges)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.btnCannyEdges = QtGui.QPushButton(self.gbEdges)
        self.btnCannyEdges.setObjectName(_fromUtf8("btnCannyEdges"))
        self.gridLayout_12.addWidget(self.btnCannyEdges, 0, 0, 1, 1)
        self.btnLaplacian = QtGui.QPushButton(self.gbEdges)
        self.btnLaplacian.setObjectName(_fromUtf8("btnLaplacian"))
        self.gridLayout_12.addWidget(self.btnLaplacian, 2, 0, 1, 1)
        self.btnSobelX = QtGui.QPushButton(self.gbEdges)
        self.btnSobelX.setObjectName(_fromUtf8("btnSobelX"))
        self.gridLayout_12.addWidget(self.btnSobelX, 3, 0, 1, 1)
        self.btnSobelY = QtGui.QPushButton(self.gbEdges)
        self.btnSobelY.setObjectName(_fromUtf8("btnSobelY"))
        self.gridLayout_12.addWidget(self.btnSobelY, 4, 0, 1, 1)
        self.gridLayout_6.addWidget(self.gbEdges, 1, 0, 1, 1)
        self.gbFitShapes = QtGui.QGroupBox(self.FindContoursTab)
        self.gbFitShapes.setObjectName(_fromUtf8("gbFitShapes"))
        self.gridLayout_13 = QtGui.QGridLayout(self.gbFitShapes)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.btnFitEllipse = QtGui.QPushButton(self.gbFitShapes)
        self.btnFitEllipse.setObjectName(_fromUtf8("btnFitEllipse"))
        self.gridLayout_13.addWidget(self.btnFitEllipse, 3, 0, 1, 1)
        self.btnFindMinCircle = QtGui.QPushButton(self.gbFitShapes)
        self.btnFindMinCircle.setObjectName(_fromUtf8("btnFindMinCircle"))
        self.gridLayout_13.addWidget(self.btnFindMinCircle, 2, 0, 1, 1)
        self.btnFindMinRectangle = QtGui.QPushButton(self.gbFitShapes)
        self.btnFindMinRectangle.setObjectName(_fromUtf8("btnFindMinRectangle"))
        self.gridLayout_13.addWidget(self.btnFindMinRectangle, 1, 0, 1, 1)
        self.btnFindRectangle = QtGui.QPushButton(self.gbFitShapes)
        self.btnFindRectangle.setObjectName(_fromUtf8("btnFindRectangle"))
        self.gridLayout_13.addWidget(self.btnFindRectangle, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.gbFitShapes, 1, 2, 1, 1)
        self.tabWidget.addTab(self.FindContoursTab, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.Buttons = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Buttons.sizePolicy().hasHeightForWidth())
        self.Buttons.setSizePolicy(sizePolicy)
        self.Buttons.setMinimumSize(QtCore.QSize(0, 0))
        self.Buttons.setTitle(_fromUtf8(""))
        self.Buttons.setObjectName(_fromUtf8("Buttons"))
        self.verticalLayout = QtGui.QVBoxLayout(self.Buttons)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.btnReset = QtGui.QPushButton(self.Buttons)
        self.btnReset.setObjectName(_fromUtf8("btnReset"))
        self.verticalLayout.addWidget(self.btnReset)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.btnApply = QtGui.QPushButton(self.Buttons)
        self.btnApply.setObjectName(_fromUtf8("btnApply"))
        self.verticalLayout.addWidget(self.btnApply)
        self.btnCancel = QtGui.QPushButton(self.Buttons)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.verticalLayout.addWidget(self.btnCancel)
        self.gridLayout_3.addWidget(self.Buttons, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1283, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionCut = QtGui.QAction(MainWindow)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSave_Image = QtGui.QAction(MainWindow)
        self.actionSave_Image.setObjectName(_fromUtf8("actionSave_Image"))
        self.actionOriginal_Image = QtGui.QAction(MainWindow)
        self.actionOriginal_Image.setObjectName(_fromUtf8("actionOriginal_Image"))
        self.actionActive_Image = QtGui.QAction(MainWindow)
        self.actionActive_Image.setObjectName(_fromUtf8("actionActive_Image"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Image)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.rbActiveImg.setText(QtGui.QApplication.translate("MainWindow", "Active/Original", None, QtGui.QApplication.UnicodeUTF8))
        self.rbOrigImg.setText(QtGui.QApplication.translate("MainWindow", "Original/Working Image", None, QtGui.QApplication.UnicodeUTF8))
        self.lblActiveImage.setText(QtGui.QApplication.translate("MainWindow", "box2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOriginalImage.setText(QtGui.QApplication.translate("MainWindow", "box1", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GreyscaleTab), QtGui.QApplication.translate("MainWindow", "Image Processing", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Color Mask HSV", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLH.setText(QtGui.QApplication.translate("MainWindow", "Lower", None, QtGui.QApplication.UnicodeUTF8))
        self.cbColorMask.setItemText(0, QtGui.QApplication.translate("MainWindow", "HSV", None, QtGui.QApplication.UnicodeUTF8))
        self.cbColorMask.setItemText(1, QtGui.QApplication.translate("MainWindow", "HSL", None, QtGui.QApplication.UnicodeUTF8))
        self.cbColorMask.setItemText(2, QtGui.QApplication.translate("MainWindow", "RGB", None, QtGui.QApplication.UnicodeUTF8))
        self.cbColorMask.setItemText(3, QtGui.QApplication.translate("MainWindow", "Lab", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCmask1_1.setText(QtGui.QApplication.translate("MainWindow", "Hue", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUV.setText(QtGui.QApplication.translate("MainWindow", "Upper", None, QtGui.QApplication.UnicodeUTF8))
        self.rbColorMask.setText(QtGui.QApplication.translate("MainWindow", "Binary/Mask", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUS.setText(QtGui.QApplication.translate("MainWindow", "Upper", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCmask2_1.setText(QtGui.QApplication.translate("MainWindow", "Saturation", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLV.setText(QtGui.QApplication.translate("MainWindow", "Lower", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLS.setText(QtGui.QApplication.translate("MainWindow", "Lower", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUH.setText(QtGui.QApplication.translate("MainWindow", "Upper", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCmask3_1.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCmask1_2.setText(QtGui.QApplication.translate("MainWindow", "Hue", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCmask2_2.setText(QtGui.QApplication.translate("MainWindow", "Saturation", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCmask3_2.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Greyscale conversions", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listGreyscale.isSortingEnabled()
        self.listGreyscale.setSortingEnabled(False)
        item = self.listGreyscale.item(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Simple Greyscale", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "---Extract RGB plane---", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Red", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Green", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(7)
        item.setText(QtGui.QApplication.translate("MainWindow", "---Extract HSV/HSL---", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(8)
        item.setText(QtGui.QApplication.translate("MainWindow", "Hue", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(9)
        item.setText(QtGui.QApplication.translate("MainWindow", "Saturation", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(10)
        item.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(11)
        item.setText(QtGui.QApplication.translate("MainWindow", "Lightness", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(13)
        item.setText(QtGui.QApplication.translate("MainWindow", "---Extract CIELAB---", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(14)
        item.setText(QtGui.QApplication.translate("MainWindow", "L*", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(15)
        item.setText(QtGui.QApplication.translate("MainWindow", "a*", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(16)
        item.setText(QtGui.QApplication.translate("MainWindow", "b*", None, QtGui.QApplication.UnicodeUTF8))
        self.listGreyscale.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabColorOps), QtGui.QApplication.translate("MainWindow", "Color Ops", None, QtGui.QApplication.UnicodeUTF8))
        self.gbHistograms.setTitle(QtGui.QApplication.translate("MainWindow", "Histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEqualizeHist.setText(QtGui.QApplication.translate("MainWindow", "Equalize", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCLAHE.setText(QtGui.QApplication.translate("MainWindow", "CLAHE", None, QtGui.QApplication.UnicodeUTF8))
        self.gbSmoothing.setTitle(QtGui.QApplication.translate("MainWindow", "Smoothing", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBlurAveraging.setText(QtGui.QApplication.translate("MainWindow", "Averaging", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBlurGaussian.setText(QtGui.QApplication.translate("MainWindow", "Gaussian", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBlurMedian.setText(QtGui.QApplication.translate("MainWindow", "Median", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFilterBilateral.setText(QtGui.QApplication.translate("MainWindow", "Bilateral", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Thresholding", None, QtGui.QApplication.UnicodeUTF8))
        self.btnThreshGlobal.setText(QtGui.QApplication.translate("MainWindow", "Global", None, QtGui.QApplication.UnicodeUTF8))
        self.btnThreshMean.setText(QtGui.QApplication.translate("MainWindow", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.btnThreshGaussian.setText(QtGui.QApplication.translate("MainWindow", "Gaussian", None, QtGui.QApplication.UnicodeUTF8))
        self.cbThreshType.setItemText(0, QtGui.QApplication.translate("MainWindow", "BINARY", None, QtGui.QApplication.UnicodeUTF8))
        self.cbThreshType.setItemText(1, QtGui.QApplication.translate("MainWindow", "BINARY_INV", None, QtGui.QApplication.UnicodeUTF8))
        self.cbThreshType.setItemText(2, QtGui.QApplication.translate("MainWindow", "TRUNC", None, QtGui.QApplication.UnicodeUTF8))
        self.cbThreshType.setItemText(3, QtGui.QApplication.translate("MainWindow", "TOZERO", None, QtGui.QApplication.UnicodeUTF8))
        self.cbThreshType.setItemText(4, QtGui.QApplication.translate("MainWindow", "TOZERO_INV", None, QtGui.QApplication.UnicodeUTF8))
        self.lblThreshThresh.setText(QtGui.QApplication.translate("MainWindow", "thresh", None, QtGui.QApplication.UnicodeUTF8))
        self.lblThreshMaxval.setText(QtGui.QApplication.translate("MainWindow", "maxval", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGreyscaleOps), QtGui.QApplication.translate("MainWindow", "Greyscale Ops", None, QtGui.QApplication.UnicodeUTF8))
        self.gbMorphology.setTitle(QtGui.QApplication.translate("MainWindow", "Morphology", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDilate.setText(QtGui.QApplication.translate("MainWindow", "Dilate", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMorphGradient.setText(QtGui.QApplication.translate("MainWindow", "Morph Gradient", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBlackHat.setText(QtGui.QApplication.translate("MainWindow", "Black Hat", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTopHat.setText(QtGui.QApplication.translate("MainWindow", "Top Hat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Kernel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.btnErode.setText(QtGui.QApplication.translate("MainWindow", "Erode", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBinaryOps), QtGui.QApplication.translate("MainWindow", "Binary Ops", None, QtGui.QApplication.UnicodeUTF8))
        self.gbEdges.setTitle(QtGui.QApplication.translate("MainWindow", "Edge Detection", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCannyEdges.setText(QtGui.QApplication.translate("MainWindow", "Canny Edges", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLaplacian.setText(QtGui.QApplication.translate("MainWindow", "Laplacian", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSobelX.setText(QtGui.QApplication.translate("MainWindow", "Sobel X", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSobelY.setText(QtGui.QApplication.translate("MainWindow", "Sobel Y", None, QtGui.QApplication.UnicodeUTF8))
        self.gbFitShapes.setTitle(QtGui.QApplication.translate("MainWindow", "Fit Shapes", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFitEllipse.setText(QtGui.QApplication.translate("MainWindow", "Fit Ellipse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFindMinCircle.setText(QtGui.QApplication.translate("MainWindow", "Min Circle", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFindMinRectangle.setText(QtGui.QApplication.translate("MainWindow", "Min Rectangle", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFindRectangle.setText(QtGui.QApplication.translate("MainWindow", "Rectangle", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FindContoursTab), QtGui.QApplication.translate("MainWindow", "Find Contours", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReset.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.btnApply.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCancel.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("MainWindow", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("MainWindow", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("MainWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Image.setText(QtGui.QApplication.translate("MainWindow", "Save Image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOriginal_Image.setText(QtGui.QApplication.translate("MainWindow", "Original Image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActive_Image.setText(QtGui.QApplication.translate("MainWindow", "Active Image", None, QtGui.QApplication.UnicodeUTF8))

