# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CVQTui2.ui'
#
# Created: Fri Jul 17 14:21:41 2015
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1283, 752)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 169, 169))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 169, 169))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 169, 169))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frame)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gbOrigRb = QtGui.QGroupBox(self.frame)
        self.gbOrigRb.setTitle(_fromUtf8(""))
        self.gbOrigRb.setObjectName(_fromUtf8("gbOrigRb"))
        self.gbImage1 = QtGui.QHBoxLayout(self.gbOrigRb)
        self.gbImage1.setSpacing(0)
        self.gbImage1.setMargin(0)
        self.gbImage1.setObjectName(_fromUtf8("gbImage1"))
        self.rbOrigWorking = QtGui.QRadioButton(self.gbOrigRb)
        self.rbOrigWorking.setChecked(True)
        self.rbOrigWorking.setAutoRepeat(False)
        self.rbOrigWorking.setAutoExclusive(True)
        self.rbOrigWorking.setObjectName(_fromUtf8("rbOrigWorking"))
        self.gbImage1.addWidget(self.rbOrigWorking)
        self.rbOrigOrig = QtGui.QRadioButton(self.gbOrigRb)
        self.rbOrigOrig.setCheckable(True)
        self.rbOrigOrig.setChecked(False)
        self.rbOrigOrig.setObjectName(_fromUtf8("rbOrigOrig"))
        self.gbImage1.addWidget(self.rbOrigOrig)
        self.rbOrigTemplate = QtGui.QRadioButton(self.gbOrigRb)
        self.rbOrigTemplate.setObjectName(_fromUtf8("rbOrigTemplate"))
        self.gbImage1.addWidget(self.rbOrigTemplate)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gbImage1.addItem(spacerItem)
        self.gridLayout_9.addWidget(self.gbOrigRb, 1, 1, 1, 1)
        self.gbActiveRb = QtGui.QGroupBox(self.frame)
        self.gbActiveRb.setTitle(_fromUtf8(""))
        self.gbActiveRb.setObjectName(_fromUtf8("gbActiveRb"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.gbActiveRb)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.rbActiveActive = QtGui.QRadioButton(self.gbActiveRb)
        self.rbActiveActive.setChecked(True)
        self.rbActiveActive.setAutoExclusive(True)
        self.rbActiveActive.setObjectName(_fromUtf8("rbActiveActive"))
        self.horizontalLayout_10.addWidget(self.rbActiveActive)
        self.rbActiveOriginal = QtGui.QRadioButton(self.gbActiveRb)
        self.rbActiveOriginal.setObjectName(_fromUtf8("rbActiveOriginal"))
        self.horizontalLayout_10.addWidget(self.rbActiveOriginal)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.gridLayout_9.addWidget(self.gbActiveRb, 1, 3, 1, 1)
        self.stackActive = QtGui.QStackedWidget(self.frame)
        self.stackActive.setObjectName(_fromUtf8("stackActive"))
        self.pageActiveImage = QtGui.QWidget()
        self.pageActiveImage.setObjectName(_fromUtf8("pageActiveImage"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.pageActiveImage)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblActiveActive = QtGui.QLabel(self.pageActiveImage)
        self.lblActiveActive.setMinimumSize(QtCore.QSize(400, 300))
        self.lblActiveActive.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lblActiveActive.setObjectName(_fromUtf8("lblActiveActive"))
        self.horizontalLayout.addWidget(self.lblActiveActive)
        self.stackActive.addWidget(self.pageActiveImage)
        self.pageWorkingImage2 = QtGui.QWidget()
        self.pageWorkingImage2.setObjectName(_fromUtf8("pageWorkingImage2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.pageWorkingImage2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.lblActiveOrig = QtGui.QLabel(self.pageWorkingImage2)
        self.lblActiveOrig.setObjectName(_fromUtf8("lblActiveOrig"))
        self.verticalLayout_7.addWidget(self.lblActiveOrig)
        self.stackActive.addWidget(self.pageWorkingImage2)
        self.gridLayout_9.addWidget(self.stackActive, 0, 3, 1, 1)
        self.stackOrig = QtGui.QStackedWidget(self.frame)
        self.stackOrig.setObjectName(_fromUtf8("stackOrig"))
        self.pageOrigWorking = QtGui.QWidget()
        self.pageOrigWorking.setObjectName(_fromUtf8("pageOrigWorking"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.pageOrigWorking)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblOrigWorking = QtGui.QLabel(self.pageOrigWorking)
        self.lblOrigWorking.setMinimumSize(QtCore.QSize(400, 300))
        self.lblOrigWorking.setAutoFillBackground(False)
        self.lblOrigWorking.setObjectName(_fromUtf8("lblOrigWorking"))
        self.horizontalLayout_2.addWidget(self.lblOrigWorking)
        self.stackOrig.addWidget(self.pageOrigWorking)
        self.pageOrigOrig = QtGui.QWidget()
        self.pageOrigOrig.setObjectName(_fromUtf8("pageOrigOrig"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.pageOrigOrig)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.lblOrigOrig = QtGui.QLabel(self.pageOrigOrig)
        self.lblOrigOrig.setObjectName(_fromUtf8("lblOrigOrig"))
        self.verticalLayout_6.addWidget(self.lblOrigOrig)
        self.stackOrig.addWidget(self.pageOrigOrig)
        self.pageOrigTemplate = QtGui.QWidget()
        self.pageOrigTemplate.setObjectName(_fromUtf8("pageOrigTemplate"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.pageOrigTemplate)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lblOrigTemplate = QtGui.QLabel(self.pageOrigTemplate)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrigTemplate.sizePolicy().hasHeightForWidth())
        self.lblOrigTemplate.setSizePolicy(sizePolicy)
        self.lblOrigTemplate.setObjectName(_fromUtf8("lblOrigTemplate"))
        self.verticalLayout_4.addWidget(self.lblOrigTemplate)
        self.stackOrig.addWidget(self.pageOrigTemplate)
        self.gridLayout_9.addWidget(self.stackOrig, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.Buttons = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Buttons.sizePolicy().hasHeightForWidth())
        self.Buttons.setSizePolicy(sizePolicy)
        self.Buttons.setMinimumSize(QtCore.QSize(0, 0))
        self.Buttons.setTitle(_fromUtf8(""))
        self.Buttons.setObjectName(_fromUtf8("Buttons"))
        self.verticalLayout = QtGui.QVBoxLayout(self.Buttons)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.btnReset = QtGui.QPushButton(self.Buttons)
        self.btnReset.setObjectName(_fromUtf8("btnReset"))
        self.verticalLayout.addWidget(self.btnReset)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.cbPicamResolution = QtGui.QComboBox(self.Buttons)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbPicamResolution.sizePolicy().hasHeightForWidth())
        self.cbPicamResolution.setSizePolicy(sizePolicy)
        self.cbPicamResolution.setObjectName(_fromUtf8("cbPicamResolution"))
        self.cbPicamResolution.addItem(_fromUtf8(""))
        self.cbPicamResolution.addItem(_fromUtf8(""))
        self.cbPicamResolution.addItem(_fromUtf8(""))
        self.cbPicamResolution.addItem(_fromUtf8(""))
        self.cbPicamResolution.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.cbPicamResolution)
        self.btnPicamSnap = QtGui.QPushButton(self.Buttons)
        self.btnPicamSnap.setObjectName(_fromUtf8("btnPicamSnap"))
        self.verticalLayout.addWidget(self.btnPicamSnap)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.gridLayout_3.addWidget(self.Buttons, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1283, 29))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(202, 500))
        self.dockWidget.setMaximumSize(QtCore.QSize(202, 524287))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 108, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(176, 172, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 54, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 72, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 108, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 181, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 108, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(176, 172, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 54, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 72, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 108, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 181, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 54, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 108, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(176, 172, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 54, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 72, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 54, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 54, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 108, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 108, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 108, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.dockWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.dockWidget.setFont(font)
        self.dockWidget.setAutoFillBackground(True)
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.dockWidgetContents.setFont(font)
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.toolBox = QtGui.QToolBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.toolBox.setFont(font)
        self.toolBox.setMouseTracking(False)
        self.toolBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.toolBox.setFrameShape(QtGui.QFrame.StyledPanel)
        self.toolBox.setFrameShadow(QtGui.QFrame.Raised)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.pageBasics = QtGui.QWidget()
        self.pageBasics.setGeometry(QtCore.QRect(0, 0, 198, 399))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageBasics.sizePolicy().hasHeightForWidth())
        self.pageBasics.setSizePolicy(sizePolicy)
        self.pageBasics.setObjectName(_fromUtf8("pageBasics"))
        self.gridLayout_21 = QtGui.QGridLayout(self.pageBasics)
        self.gridLayout_21.setContentsMargins(2, 0, 2, 0)
        self.gridLayout_21.setHorizontalSpacing(10)
        self.gridLayout_21.setVerticalSpacing(0)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.lblScale = QtGui.QLabel(self.pageBasics)
        self.lblScale.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblScale.setObjectName(_fromUtf8("lblScale"))
        self.gridLayout_21.addWidget(self.lblScale, 4, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem4, 7, 0, 1, 2)
        self.groupBox_9 = QtGui.QGroupBox(self.pageBasics)
        self.groupBox_9.setEnabled(True)
        self.groupBox_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_20 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.btnRotate270 = QtGui.QPushButton(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRotate270.sizePolicy().hasHeightForWidth())
        self.btnRotate270.setSizePolicy(sizePolicy)
        self.btnRotate270.setObjectName(_fromUtf8("btnRotate270"))
        self.gridLayout_20.addWidget(self.btnRotate270, 1, 0, 1, 1)
        self.lblRotateDegrees = QtGui.QLabel(self.groupBox_9)
        self.lblRotateDegrees.setObjectName(_fromUtf8("lblRotateDegrees"))
        self.gridLayout_20.addWidget(self.lblRotateDegrees, 3, 1, 1, 1)
        self.btnRotate90 = QtGui.QPushButton(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRotate90.sizePolicy().hasHeightForWidth())
        self.btnRotate90.setSizePolicy(sizePolicy)
        self.btnRotate90.setObjectName(_fromUtf8("btnRotate90"))
        self.gridLayout_20.addWidget(self.btnRotate90, 0, 0, 1, 1)
        self.sbRotateX = QtGui.QSpinBox(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbRotateX.sizePolicy().hasHeightForWidth())
        self.sbRotateX.setSizePolicy(sizePolicy)
        self.sbRotateX.setMaximum(360)
        self.sbRotateX.setObjectName(_fromUtf8("sbRotateX"))
        self.gridLayout_20.addWidget(self.sbRotateX, 3, 0, 1, 1)
        self.btnRotate180 = QtGui.QPushButton(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRotate180.sizePolicy().hasHeightForWidth())
        self.btnRotate180.setSizePolicy(sizePolicy)
        self.btnRotate180.setObjectName(_fromUtf8("btnRotate180"))
        self.gridLayout_20.addWidget(self.btnRotate180, 0, 1, 1, 1)
        self.gridLayout_21.addWidget(self.groupBox_9, 0, 0, 1, 2)
        self.pbMirror = QtGui.QPushButton(self.pageBasics)
        self.pbMirror.setObjectName(_fromUtf8("pbMirror"))
        self.gridLayout_21.addWidget(self.pbMirror, 1, 0, 1, 2)
        self.dsbScale = QtGui.QDoubleSpinBox(self.pageBasics)
        self.dsbScale.setObjectName(_fromUtf8("dsbScale"))
        self.gridLayout_21.addWidget(self.dsbScale, 4, 1, 1, 1)
        self.toolBox.addItem(self.pageBasics, _fromUtf8(""))
        self.pageROI = QtGui.QWidget()
        self.pageROI.setGeometry(QtCore.QRect(0, 0, 198, 399))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageROI.sizePolicy().hasHeightForWidth())
        self.pageROI.setSizePolicy(sizePolicy)
        self.pageROI.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setItalic(False)
        self.pageROI.setFont(font)
        self.pageROI.setObjectName(_fromUtf8("pageROI"))
        self.gridLayout_2 = QtGui.QGridLayout(self.pageROI)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 7, 0, 1, 4)
        self.gbROI = QtGui.QGroupBox(self.pageROI)
        self.gbROI.setMinimumSize(QtCore.QSize(0, 0))
        self.gbROI.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gbROI.setObjectName(_fromUtf8("gbROI"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gbROI)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setContentsMargins(2, 0, 2, 2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_2 = QtGui.QLabel(self.gbROI)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 6, 1, 1, 4)
        self.label = QtGui.QLabel(self.gbROI)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 3, 1, 1, 4)
        self.rbROIEnable = QtGui.QRadioButton(self.gbROI)
        self.rbROIEnable.setAutoExclusive(False)
        self.rbROIEnable.setObjectName(_fromUtf8("rbROIEnable"))
        self.gridLayout_4.addWidget(self.rbROIEnable, 0, 1, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.sliderROITop = QtGui.QSlider(self.gbROI)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderROITop.sizePolicy().hasHeightForWidth())
        self.sliderROITop.setSizePolicy(sizePolicy)
        self.sliderROITop.setMaximumSize(QtCore.QSize(16777215, 150))
        self.sliderROITop.setMaximum(100)
        self.sliderROITop.setProperty("value", 0)
        self.sliderROITop.setOrientation(QtCore.Qt.Vertical)
        self.sliderROITop.setInvertedAppearance(True)
        self.sliderROITop.setObjectName(_fromUtf8("sliderROITop"))
        self.gridLayout_5.addWidget(self.sliderROITop, 0, 1, 1, 1)
        self.lblROIBottom = QtGui.QLabel(self.gbROI)
        self.lblROIBottom.setObjectName(_fromUtf8("lblROIBottom"))
        self.gridLayout_5.addWidget(self.lblROIBottom, 1, 0, 1, 1)
        self.lblROITop = QtGui.QLabel(self.gbROI)
        self.lblROITop.setObjectName(_fromUtf8("lblROITop"))
        self.gridLayout_5.addWidget(self.lblROITop, 1, 1, 1, 1)
        self.sliderROIBottom = QtGui.QSlider(self.gbROI)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderROIBottom.sizePolicy().hasHeightForWidth())
        self.sliderROIBottom.setSizePolicy(sizePolicy)
        self.sliderROIBottom.setMaximum(100)
        self.sliderROIBottom.setOrientation(QtCore.Qt.Vertical)
        self.sliderROIBottom.setObjectName(_fromUtf8("sliderROIBottom"))
        self.gridLayout_5.addWidget(self.sliderROIBottom, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 9, 1, 1, 2)
        self.sliderROILeft = QtGui.QSlider(self.gbROI)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderROILeft.sizePolicy().hasHeightForWidth())
        self.sliderROILeft.setSizePolicy(sizePolicy)
        self.sliderROILeft.setMinimumSize(QtCore.QSize(170, 0))
        self.sliderROILeft.setMaximum(100)
        self.sliderROILeft.setOrientation(QtCore.Qt.Horizontal)
        self.sliderROILeft.setObjectName(_fromUtf8("sliderROILeft"))
        self.gridLayout_4.addWidget(self.sliderROILeft, 4, 1, 1, 1)
        self.sliderROIRight = QtGui.QSlider(self.gbROI)
        self.sliderROIRight.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderROIRight.sizePolicy().hasHeightForWidth())
        self.sliderROIRight.setSizePolicy(sizePolicy)
        self.sliderROIRight.setMinimumSize(QtCore.QSize(0, 0))
        self.sliderROIRight.setMaximum(100)
        self.sliderROIRight.setProperty("value", 0)
        self.sliderROIRight.setOrientation(QtCore.Qt.Horizontal)
        self.sliderROIRight.setInvertedAppearance(True)
        self.sliderROIRight.setInvertedControls(False)
        self.sliderROIRight.setObjectName(_fromUtf8("sliderROIRight"))
        self.gridLayout_4.addWidget(self.sliderROIRight, 7, 1, 1, 4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.rbROICrop = QtGui.QRadioButton(self.gbROI)
        self.rbROICrop.setChecked(True)
        self.rbROICrop.setObjectName(_fromUtf8("rbROICrop"))
        self.horizontalLayout_3.addWidget(self.rbROICrop)
        self.rbROIMask = QtGui.QRadioButton(self.gbROI)
        self.rbROIMask.setObjectName(_fromUtf8("rbROIMask"))
        self.horizontalLayout_3.addWidget(self.rbROIMask)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.gbROI, 0, 2, 1, 1)
        self.gbMoment = QtGui.QGroupBox(self.pageROI)
        self.gbMoment.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gbMoment.setObjectName(_fromUtf8("gbMoment"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gbMoment)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(2, 0, 2, 0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.rbMomentEnable = QtGui.QRadioButton(self.gbMoment)
        self.rbMomentEnable.setObjectName(_fromUtf8("rbMomentEnable"))
        self.verticalLayout_2.addWidget(self.rbMomentEnable)
        self.lblMomentMin = QtGui.QLabel(self.gbMoment)
        self.lblMomentMin.setObjectName(_fromUtf8("lblMomentMin"))
        self.verticalLayout_2.addWidget(self.lblMomentMin)
        self.sbMomentMin = QtGui.QSpinBox(self.gbMoment)
        self.sbMomentMin.setMaximum(50000)
        self.sbMomentMin.setObjectName(_fromUtf8("sbMomentMin"))
        self.verticalLayout_2.addWidget(self.sbMomentMin)
        self.sliderMomentMin = QtGui.QSlider(self.gbMoment)
        self.sliderMomentMin.setMaximum(50000)
        self.sliderMomentMin.setOrientation(QtCore.Qt.Horizontal)
        self.sliderMomentMin.setObjectName(_fromUtf8("sliderMomentMin"))
        self.verticalLayout_2.addWidget(self.sliderMomentMin)
        self.lblMomentMax = QtGui.QLabel(self.gbMoment)
        self.lblMomentMax.setObjectName(_fromUtf8("lblMomentMax"))
        self.verticalLayout_2.addWidget(self.lblMomentMax)
        self.sbMomentMax = QtGui.QSpinBox(self.gbMoment)
        self.sbMomentMax.setMaximum(50000)
        self.sbMomentMax.setProperty("value", 50000)
        self.sbMomentMax.setObjectName(_fromUtf8("sbMomentMax"))
        self.verticalLayout_2.addWidget(self.sbMomentMax)
        self.sliderMomentMax = QtGui.QSlider(self.gbMoment)
        self.sliderMomentMax.setMaximum(50000)
        self.sliderMomentMax.setProperty("value", 50000)
        self.sliderMomentMax.setOrientation(QtCore.Qt.Horizontal)
        self.sliderMomentMax.setObjectName(_fromUtf8("sliderMomentMax"))
        self.verticalLayout_2.addWidget(self.sliderMomentMax)
        self.gridLayout_2.addWidget(self.gbMoment, 1, 2, 1, 1)
        self.toolBox.addItem(self.pageROI, _fromUtf8(""))
        self.pageColorOps = QtGui.QWidget()
        self.pageColorOps.setGeometry(QtCore.QRect(0, 0, 198, 399))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageColorOps.sizePolicy().hasHeightForWidth())
        self.pageColorOps.setSizePolicy(sizePolicy)
        self.pageColorOps.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pageColorOps.setObjectName(_fromUtf8("pageColorOps"))
        self.gridLayout_16 = QtGui.QGridLayout(self.pageColorOps)
        self.gridLayout_16.setMargin(2)
        self.gridLayout_16.setHorizontalSpacing(0)
        self.gridLayout_16.setVerticalSpacing(2)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.gbColorMask = QtGui.QGroupBox(self.pageColorOps)
        self.gbColorMask.setObjectName(_fromUtf8("gbColorMask"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gbColorMask)
        self.gridLayout_8.setMargin(2)
        self.gridLayout_8.setSpacing(2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.rbColorMask = QtGui.QRadioButton(self.gbColorMask)
        self.rbColorMask.setObjectName(_fromUtf8("rbColorMask"))
        self.gridLayout_8.addWidget(self.rbColorMask, 0, 6, 1, 2)
        self.cbColorMask = QtGui.QComboBox(self.gbColorMask)
        self.cbColorMask.setObjectName(_fromUtf8("cbColorMask"))
        self.cbColorMask.addItem(_fromUtf8(""))
        self.cbColorMask.addItem(_fromUtf8(""))
        self.cbColorMask.addItem(_fromUtf8(""))
        self.cbColorMask.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.cbColorMask, 0, 5, 1, 1)
        self.lblCmask2_1 = QtGui.QLabel(self.gbColorMask)
        self.lblCmask2_1.setObjectName(_fromUtf8("lblCmask2_1"))
        self.gridLayout_8.addWidget(self.lblCmask2_1, 2, 5, 1, 1)
        self.lblCmask1_1 = QtGui.QLabel(self.gbColorMask)
        self.lblCmask1_1.setObjectName(_fromUtf8("lblCmask1_1"))
        self.gridLayout_8.addWidget(self.lblCmask1_1, 1, 5, 1, 1)
        self.sbLH = QtGui.QSpinBox(self.gbColorMask)
        self.sbLH.setMaximum(255)
        self.sbLH.setObjectName(_fromUtf8("sbLH"))
        self.gridLayout_8.addWidget(self.sbLH, 1, 6, 1, 1)
        self.sbUH = QtGui.QSpinBox(self.gbColorMask)
        self.sbUH.setMaximum(255)
        self.sbUH.setProperty("value", 255)
        self.sbUH.setObjectName(_fromUtf8("sbUH"))
        self.gridLayout_8.addWidget(self.sbUH, 1, 7, 1, 1)
        self.lblCmask3_1 = QtGui.QLabel(self.gbColorMask)
        self.lblCmask3_1.setObjectName(_fromUtf8("lblCmask3_1"))
        self.gridLayout_8.addWidget(self.lblCmask3_1, 3, 5, 1, 1)
        self.sbLS = QtGui.QSpinBox(self.gbColorMask)
        self.sbLS.setMaximum(255)
        self.sbLS.setObjectName(_fromUtf8("sbLS"))
        self.gridLayout_8.addWidget(self.sbLS, 2, 6, 1, 1)
        self.sbLV = QtGui.QSpinBox(self.gbColorMask)
        self.sbLV.setMaximum(255)
        self.sbLV.setObjectName(_fromUtf8("sbLV"))
        self.gridLayout_8.addWidget(self.sbLV, 3, 6, 1, 1)
        self.sbUS = QtGui.QSpinBox(self.gbColorMask)
        self.sbUS.setMaximum(255)
        self.sbUS.setProperty("value", 255)
        self.sbUS.setObjectName(_fromUtf8("sbUS"))
        self.gridLayout_8.addWidget(self.sbUS, 2, 7, 1, 1)
        self.sbUV = QtGui.QSpinBox(self.gbColorMask)
        self.sbUV.setMaximum(255)
        self.sbUV.setProperty("value", 255)
        self.sbUV.setObjectName(_fromUtf8("sbUV"))
        self.gridLayout_8.addWidget(self.sbUV, 3, 7, 1, 1)
        self.gridLayout_16.addWidget(self.gbColorMask, 6, 0, 1, 3)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem6, 8, 0, 1, 3)
        self.gbGreyscale = QtGui.QGroupBox(self.pageColorOps)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbGreyscale.sizePolicy().hasHeightForWidth())
        self.gbGreyscale.setSizePolicy(sizePolicy)
        self.gbGreyscale.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gbGreyscale.setObjectName(_fromUtf8("gbGreyscale"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gbGreyscale)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setContentsMargins(0, 0, 4, 0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.listGreyscale = QtGui.QListWidget(self.gbGreyscale)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listGreyscale.sizePolicy().hasHeightForWidth())
        self.listGreyscale.setSizePolicy(sizePolicy)
        self.listGreyscale.setFrameShape(QtGui.QFrame.StyledPanel)
        self.listGreyscale.setObjectName(_fromUtf8("listGreyscale"))
        item = QtGui.QListWidgetItem()
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        font = QtGui.QFont()
        font.setKerning(True)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listGreyscale.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listGreyscale.addItem(item)
        self.gridLayout_7.addWidget(self.listGreyscale, 0, 2, 1, 1)
        self.gridLayout_16.addWidget(self.gbGreyscale, 7, 0, 1, 3)
        self.toolBox.addItem(self.pageColorOps, _fromUtf8(""))
        self.pageGreyscaleOps = QtGui.QWidget()
        self.pageGreyscaleOps.setGeometry(QtCore.QRect(0, 0, 198, 399))
        self.pageGreyscaleOps.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pageGreyscaleOps.setObjectName(_fromUtf8("pageGreyscaleOps"))
        self.gridLayout_15 = QtGui.QGridLayout(self.pageGreyscaleOps)
        self.gridLayout_15.setSpacing(2)
        self.gridLayout_15.setContentsMargins(4, 2, 2, 2)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.gbThresholding = QtGui.QGroupBox(self.pageGreyscaleOps)
        self.gbThresholding.setObjectName(_fromUtf8("gbThresholding"))
        self.gridLayout_14 = QtGui.QGridLayout(self.gbThresholding)
        self.gridLayout_14.setMargin(2)
        self.gridLayout_14.setSpacing(2)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.btnThreshGlobal = QtGui.QPushButton(self.gbThresholding)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnThreshGlobal.sizePolicy().hasHeightForWidth())
        self.btnThreshGlobal.setSizePolicy(sizePolicy)
        self.btnThreshGlobal.setObjectName(_fromUtf8("btnThreshGlobal"))
        self.gridLayout_14.addWidget(self.btnThreshGlobal, 0, 0, 1, 1)
        self.btnThreshMean = QtGui.QPushButton(self.gbThresholding)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnThreshMean.sizePolicy().hasHeightForWidth())
        self.btnThreshMean.setSizePolicy(sizePolicy)
        self.btnThreshMean.setObjectName(_fromUtf8("btnThreshMean"))
        self.gridLayout_14.addWidget(self.btnThreshMean, 2, 0, 1, 1)
        self.btnThreshGaussian = QtGui.QPushButton(self.gbThresholding)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnThreshGaussian.sizePolicy().hasHeightForWidth())
        self.btnThreshGaussian.setSizePolicy(sizePolicy)
        self.btnThreshGaussian.setObjectName(_fromUtf8("btnThreshGaussian"))
        self.gridLayout_14.addWidget(self.btnThreshGaussian, 3, 0, 1, 1)
        self.cbThreshType = QtGui.QComboBox(self.gbThresholding)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbThreshType.sizePolicy().hasHeightForWidth())
        self.cbThreshType.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbThreshType.setFont(font)
        self.cbThreshType.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.cbThreshType.setMinimumContentsLength(5)
        self.cbThreshType.setObjectName(_fromUtf8("cbThreshType"))
        self.cbThreshType.addItem(_fromUtf8(""))
        self.cbThreshType.addItem(_fromUtf8(""))
        self.cbThreshType.addItem(_fromUtf8(""))
        self.cbThreshType.addItem(_fromUtf8(""))
        self.cbThreshType.addItem(_fromUtf8(""))
        self.gridLayout_14.addWidget(self.cbThreshType, 0, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lblThreshMaxval = QtGui.QLabel(self.gbThresholding)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblThreshMaxval.sizePolicy().hasHeightForWidth())
        self.lblThreshMaxval.setSizePolicy(sizePolicy)
        self.lblThreshMaxval.setObjectName(_fromUtf8("lblThreshMaxval"))
        self.horizontalLayout_5.addWidget(self.lblThreshMaxval)
        self.sbThreshMaxval = QtGui.QSpinBox(self.gbThresholding)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbThreshMaxval.sizePolicy().hasHeightForWidth())
        self.sbThreshMaxval.setSizePolicy(sizePolicy)
        self.sbThreshMaxval.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sbThreshMaxval.setFrame(False)
        self.sbThreshMaxval.setMaximum(255)
        self.sbThreshMaxval.setProperty("value", 255)
        self.sbThreshMaxval.setObjectName(_fromUtf8("sbThreshMaxval"))
        self.horizontalLayout_5.addWidget(self.sbThreshMaxval)
        self.gridLayout_14.addLayout(self.horizontalLayout_5, 3, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lblThreshThresh = QtGui.QLabel(self.gbThresholding)
        self.lblThreshThresh.setObjectName(_fromUtf8("lblThreshThresh"))
        self.horizontalLayout_4.addWidget(self.lblThreshThresh)
        self.sbThreshThresh = QtGui.QSpinBox(self.gbThresholding)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbThreshThresh.sizePolicy().hasHeightForWidth())
        self.sbThreshThresh.setSizePolicy(sizePolicy)
        self.sbThreshThresh.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sbThreshThresh.setFrame(False)
        self.sbThreshThresh.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sbThreshThresh.setMaximum(255)
        self.sbThreshThresh.setProperty("value", 127)
        self.sbThreshThresh.setObjectName(_fromUtf8("sbThreshThresh"))
        self.horizontalLayout_4.addWidget(self.sbThreshThresh)
        self.gridLayout_14.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.gridLayout_15.addWidget(self.gbThresholding, 2, 0, 1, 1)
        self.gbHistograms = QtGui.QGroupBox(self.pageGreyscaleOps)
        self.gbHistograms.setObjectName(_fromUtf8("gbHistograms"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.gbHistograms)
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setContentsMargins(2, 4, 2, 4)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btnEqualizeHist = QtGui.QPushButton(self.gbHistograms)
        self.btnEqualizeHist.setObjectName(_fromUtf8("btnEqualizeHist"))
        self.horizontalLayout_6.addWidget(self.btnEqualizeHist)
        self.btnCLAHE = QtGui.QPushButton(self.gbHistograms)
        self.btnCLAHE.setObjectName(_fromUtf8("btnCLAHE"))
        self.horizontalLayout_6.addWidget(self.btnCLAHE)
        self.gridLayout_15.addWidget(self.gbHistograms, 0, 0, 1, 1)
        self.gbSmoothing = QtGui.QGroupBox(self.pageGreyscaleOps)
        self.gbSmoothing.setObjectName(_fromUtf8("gbSmoothing"))
        self.gridLayout_17 = QtGui.QGridLayout(self.gbSmoothing)
        self.gridLayout_17.setMargin(2)
        self.gridLayout_17.setSpacing(2)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.btnBlurMedian = QtGui.QPushButton(self.gbSmoothing)
        self.btnBlurMedian.setObjectName(_fromUtf8("btnBlurMedian"))
        self.gridLayout_17.addWidget(self.btnBlurMedian, 2, 0, 1, 1)
        self.btnBlurAveraging = QtGui.QPushButton(self.gbSmoothing)
        self.btnBlurAveraging.setObjectName(_fromUtf8("btnBlurAveraging"))
        self.gridLayout_17.addWidget(self.btnBlurAveraging, 0, 0, 1, 1)
        self.btnBlurGaussian = QtGui.QPushButton(self.gbSmoothing)
        self.btnBlurGaussian.setObjectName(_fromUtf8("btnBlurGaussian"))
        self.gridLayout_17.addWidget(self.btnBlurGaussian, 0, 1, 1, 1)
        self.btnFilterBilateral = QtGui.QPushButton(self.gbSmoothing)
        self.btnFilterBilateral.setObjectName(_fromUtf8("btnFilterBilateral"))
        self.gridLayout_17.addWidget(self.btnFilterBilateral, 2, 1, 1, 1)
        self.gridLayout_15.addWidget(self.gbSmoothing, 1, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem7, 3, 0, 1, 1)
        self.toolBox.addItem(self.pageGreyscaleOps, _fromUtf8(""))
        self.pageBinaryOps = QtGui.QWidget()
        self.pageBinaryOps.setGeometry(QtCore.QRect(0, 0, 198, 399))
        self.pageBinaryOps.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pageBinaryOps.setObjectName(_fromUtf8("pageBinaryOps"))
        self.gridLayout_18 = QtGui.QGridLayout(self.pageBinaryOps)
        self.gridLayout_18.setContentsMargins(4, -1, 4, -1)
        self.gridLayout_18.setHorizontalSpacing(0)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.gbMorphology = QtGui.QGroupBox(self.pageBinaryOps)
        self.gbMorphology.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gbMorphology.setObjectName(_fromUtf8("gbMorphology"))
        self.gridLayout_11 = QtGui.QGridLayout(self.gbMorphology)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setSpacing(2)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.btnDilate = QtGui.QPushButton(self.gbMorphology)
        self.btnDilate.setObjectName(_fromUtf8("btnDilate"))
        self.gridLayout_11.addWidget(self.btnDilate, 1, 2, 1, 1)
        self.btnClose = QtGui.QPushButton(self.gbMorphology)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.gridLayout_11.addWidget(self.btnClose, 2, 2, 1, 1)
        self.btnOpen = QtGui.QPushButton(self.gbMorphology)
        self.btnOpen.setObjectName(_fromUtf8("btnOpen"))
        self.gridLayout_11.addWidget(self.btnOpen, 2, 0, 1, 1)
        self.btnMorphGradient = QtGui.QPushButton(self.gbMorphology)
        self.btnMorphGradient.setObjectName(_fromUtf8("btnMorphGradient"))
        self.gridLayout_11.addWidget(self.btnMorphGradient, 3, 0, 1, 1)
        self.btnBlackHat = QtGui.QPushButton(self.gbMorphology)
        self.btnBlackHat.setObjectName(_fromUtf8("btnBlackHat"))
        self.gridLayout_11.addWidget(self.btnBlackHat, 4, 2, 1, 1)
        self.btnTopHat = QtGui.QPushButton(self.gbMorphology)
        self.btnTopHat.setObjectName(_fromUtf8("btnTopHat"))
        self.gridLayout_11.addWidget(self.btnTopHat, 3, 2, 1, 1)
        self.btnErode = QtGui.QPushButton(self.gbMorphology)
        self.btnErode.setStyleSheet(_fromUtf8(""))
        self.btnErode.setObjectName(_fromUtf8("btnErode"))
        self.gridLayout_11.addWidget(self.btnErode, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_7 = QtGui.QLabel(self.gbMorphology)
        self.label_7.setMinimumSize(QtCore.QSize(40, 0))
        self.label_7.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        self.sbKernel1 = QtGui.QSpinBox(self.gbMorphology)
        self.sbKernel1.setMinimumSize(QtCore.QSize(45, 30))
        self.sbKernel1.setMaximumSize(QtCore.QSize(45, 30))
        self.sbKernel1.setMinimum(1)
        self.sbKernel1.setMaximum(20)
        self.sbKernel1.setProperty("value", 5)
        self.sbKernel1.setObjectName(_fromUtf8("sbKernel1"))
        self.horizontalLayout_8.addWidget(self.sbKernel1)
        self.gridLayout_11.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_5 = QtGui.QLabel(self.gbMorphology)
        self.label_5.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        self.sbKernel2 = QtGui.QSpinBox(self.gbMorphology)
        self.sbKernel2.setMinimumSize(QtCore.QSize(45, 30))
        self.sbKernel2.setMaximumSize(QtCore.QSize(45, 30))
        self.sbKernel2.setMinimum(1)
        self.sbKernel2.setMaximum(20)
        self.sbKernel2.setProperty("value", 5)
        self.sbKernel2.setObjectName(_fromUtf8("sbKernel2"))
        self.horizontalLayout_7.addWidget(self.sbKernel2)
        self.gridLayout_11.addLayout(self.horizontalLayout_7, 0, 2, 1, 1)
        self.gridLayout_18.addWidget(self.gbMorphology, 0, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem8, 1, 0, 1, 1)
        self.toolBox.addItem(self.pageBinaryOps, _fromUtf8(""))
        self.pageFindContours = QtGui.QWidget()
        self.pageFindContours.setGeometry(QtCore.QRect(0, 0, 198, 399))
        self.pageFindContours.setMinimumSize(QtCore.QSize(0, 0))
        self.pageFindContours.setObjectName(_fromUtf8("pageFindContours"))
        self.gridLayout_19 = QtGui.QGridLayout(self.pageFindContours)
        self.gridLayout_19.setContentsMargins(0, 2, 2, 2)
        self.gridLayout_19.setHorizontalSpacing(0)
        self.gridLayout_19.setVerticalSpacing(2)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.gbEdges = QtGui.QGroupBox(self.pageFindContours)
        self.gbEdges.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gbEdges.setObjectName(_fromUtf8("gbEdges"))
        self.gridLayout_12 = QtGui.QGridLayout(self.gbEdges)
        self.gridLayout_12.setMargin(2)
        self.gridLayout_12.setSpacing(2)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.btnSobelY = QtGui.QPushButton(self.gbEdges)
        self.btnSobelY.setObjectName(_fromUtf8("btnSobelY"))
        self.gridLayout_12.addWidget(self.btnSobelY, 3, 1, 1, 1)
        self.btnCannyEdges = QtGui.QPushButton(self.gbEdges)
        self.btnCannyEdges.setObjectName(_fromUtf8("btnCannyEdges"))
        self.gridLayout_12.addWidget(self.btnCannyEdges, 0, 0, 1, 1)
        self.btnSobelX = QtGui.QPushButton(self.gbEdges)
        self.btnSobelX.setObjectName(_fromUtf8("btnSobelX"))
        self.gridLayout_12.addWidget(self.btnSobelX, 3, 0, 1, 1)
        self.btnLaplacian = QtGui.QPushButton(self.gbEdges)
        self.btnLaplacian.setObjectName(_fromUtf8("btnLaplacian"))
        self.gridLayout_12.addWidget(self.btnLaplacian, 0, 1, 1, 1)
        self.gridLayout_19.addWidget(self.gbEdges, 0, 0, 1, 1)
        self.gbFitShapes = QtGui.QGroupBox(self.pageFindContours)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbFitShapes.sizePolicy().hasHeightForWidth())
        self.gbFitShapes.setSizePolicy(sizePolicy)
        self.gbFitShapes.setObjectName(_fromUtf8("gbFitShapes"))
        self.gridLayout_13 = QtGui.QGridLayout(self.gbFitShapes)
        self.gridLayout_13.setMargin(2)
        self.gridLayout_13.setSpacing(2)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.btnFindMinCircle = QtGui.QPushButton(self.gbFitShapes)
        self.btnFindMinCircle.setObjectName(_fromUtf8("btnFindMinCircle"))
        self.gridLayout_13.addWidget(self.btnFindMinCircle, 3, 0, 1, 1)
        self.btnFindRectangle = QtGui.QPushButton(self.gbFitShapes)
        self.btnFindRectangle.setObjectName(_fromUtf8("btnFindRectangle"))
        self.gridLayout_13.addWidget(self.btnFindRectangle, 0, 0, 1, 1)
        self.btnFindMinRectangle = QtGui.QPushButton(self.gbFitShapes)
        self.btnFindMinRectangle.setObjectName(_fromUtf8("btnFindMinRectangle"))
        self.gridLayout_13.addWidget(self.btnFindMinRectangle, 0, 1, 1, 1)
        self.btnFitEllipse = QtGui.QPushButton(self.gbFitShapes)
        self.btnFitEllipse.setObjectName(_fromUtf8("btnFitEllipse"))
        self.gridLayout_13.addWidget(self.btnFitEllipse, 3, 1, 1, 1)
        self.gridLayout_19.addWidget(self.gbFitShapes, 1, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem9, 2, 0, 1, 1)
        self.toolBox.addItem(self.pageFindContours, _fromUtf8(""))
        self.pageFeatureDetection = QtGui.QWidget()
        self.pageFeatureDetection.setGeometry(QtCore.QRect(0, 0, 198, 399))
        self.pageFeatureDetection.setObjectName(_fromUtf8("pageFeatureDetection"))
        self.gridLayout_6 = QtGui.QGridLayout(self.pageFeatureDetection)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setContentsMargins(0, 4, 0, 0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gbTemplate = QtGui.QGroupBox(self.pageFeatureDetection)
        self.gbTemplate.setObjectName(_fromUtf8("gbTemplate"))
        self.gridLayout_10 = QtGui.QGridLayout(self.gbTemplate)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.btnTemplateFind = QtGui.QPushButton(self.gbTemplate)
        self.btnTemplateFind.setObjectName(_fromUtf8("btnTemplateFind"))
        self.gridLayout_10.addWidget(self.btnTemplateFind, 1, 0, 1, 1)
        self.cbTemplateMethod = QtGui.QComboBox(self.gbTemplate)
        self.cbTemplateMethod.setObjectName(_fromUtf8("cbTemplateMethod"))
        self.cbTemplateMethod.addItem(_fromUtf8(""))
        self.cbTemplateMethod.addItem(_fromUtf8(""))
        self.cbTemplateMethod.addItem(_fromUtf8(""))
        self.cbTemplateMethod.addItem(_fromUtf8(""))
        self.cbTemplateMethod.addItem(_fromUtf8(""))
        self.cbTemplateMethod.addItem(_fromUtf8(""))
        self.gridLayout_10.addWidget(self.cbTemplateMethod, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.gbTemplate, 4, 0, 1, 2)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem10, 5, 0, 1, 2)
        self.toolBox.addItem(self.pageFeatureDetection, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.toolBox)
        self.btnApply = QtGui.QPushButton(self.dockWidgetContents)
        self.btnApply.setObjectName(_fromUtf8("btnApply"))
        self.verticalLayout_3.addWidget(self.btnApply)
        self.btnCancel = QtGui.QPushButton(self.dockWidgetContents)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.verticalLayout_3.addWidget(self.btnCancel)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionCut = QtGui.QAction(MainWindow)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSave_Image = QtGui.QAction(MainWindow)
        self.actionSave_Image.setObjectName(_fromUtf8("actionSave_Image"))
        self.actionOriginal_Image = QtGui.QAction(MainWindow)
        self.actionOriginal_Image.setObjectName(_fromUtf8("actionOriginal_Image"))
        self.actionActive_Image = QtGui.QAction(MainWindow)
        self.actionActive_Image.setObjectName(_fromUtf8("actionActive_Image"))
        self.actionLoad_template = QtGui.QAction(MainWindow)
        self.actionLoad_template.setObjectName(_fromUtf8("actionLoad_template"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionLoad_template)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Image)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackActive.setCurrentIndex(0)
        self.stackOrig.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(2)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.sbMomentMin, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.sliderMomentMin.setValue)
        QtCore.QObject.connect(self.sbMomentMax, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.sliderMomentMax.setValue)
        QtCore.QObject.connect(self.sliderMomentMin, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.sbMomentMin.setValue)
        QtCore.QObject.connect(self.sliderMomentMax, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.sbMomentMax.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.rbOrigWorking.setText(QtGui.QApplication.translate("MainWindow", "Working Image", None, QtGui.QApplication.UnicodeUTF8))
        self.rbOrigOrig.setText(QtGui.QApplication.translate("MainWindow", "Original Image", None, QtGui.QApplication.UnicodeUTF8))
        self.rbOrigTemplate.setText(QtGui.QApplication.translate("MainWindow", "Template Image", None, QtGui.QApplication.UnicodeUTF8))
        self.rbActiveActive.setText(QtGui.QApplication.translate("MainWindow", "Active Image", None, QtGui.QApplication.UnicodeUTF8))
        self.rbActiveOriginal.setText(QtGui.QApplication.translate("MainWindow", "Original Image", None, QtGui.QApplication.UnicodeUTF8))
        self.lblActiveActive.setText(QtGui.QApplication.translate("MainWindow", "active", None, QtGui.QApplication.UnicodeUTF8))
        self.lblActiveOrig.setText(QtGui.QApplication.translate("MainWindow", "orig", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOrigWorking.setText(QtGui.QApplication.translate("MainWindow", "working", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOrigOrig.setText(QtGui.QApplication.translate("MainWindow", "orig", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOrigTemplate.setText(QtGui.QApplication.translate("MainWindow", "template", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReset.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.cbPicamResolution.setItemText(0, QtGui.QApplication.translate("MainWindow", "640x480", None, QtGui.QApplication.UnicodeUTF8))
        self.cbPicamResolution.setItemText(1, QtGui.QApplication.translate("MainWindow", "960x720", None, QtGui.QApplication.UnicodeUTF8))
        self.cbPicamResolution.setItemText(2, QtGui.QApplication.translate("MainWindow", "1280x960", None, QtGui.QApplication.UnicodeUTF8))
        self.cbPicamResolution.setItemText(3, QtGui.QApplication.translate("MainWindow", "1440x1080", None, QtGui.QApplication.UnicodeUTF8))
        self.cbPicamResolution.setItemText(4, QtGui.QApplication.translate("MainWindow", "2592x1944", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPicamSnap.setText(QtGui.QApplication.translate("MainWindow", "PiCam Snap", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Awesomeness Here", None, QtGui.QApplication.UnicodeUTF8))
        self.lblScale.setText(QtGui.QApplication.translate("MainWindow", "Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("MainWindow", "Rotate", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRotate270.setText(QtGui.QApplication.translate("MainWindow", "270 Degees", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRotateDegrees.setText(QtGui.QApplication.translate("MainWindow", "Degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRotate90.setText(QtGui.QApplication.translate("MainWindow", "90 Degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRotate180.setText(QtGui.QApplication.translate("MainWindow", "180 Degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.pbMirror.setText(QtGui.QApplication.translate("MainWindow", "Mirror", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageBasics), QtGui.QApplication.translate("MainWindow", "Basics", None, QtGui.QApplication.UnicodeUTF8))
        self.gbROI.setTitle(QtGui.QApplication.translate("MainWindow", "ROI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.rbROIEnable.setText(QtGui.QApplication.translate("MainWindow", "Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.lblROIBottom.setText(QtGui.QApplication.translate("MainWindow", "Bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.lblROITop.setText(QtGui.QApplication.translate("MainWindow", "Top", None, QtGui.QApplication.UnicodeUTF8))
        self.rbROICrop.setText(QtGui.QApplication.translate("MainWindow", "Crop", None, QtGui.QApplication.UnicodeUTF8))
        self.rbROIMask.setText(QtGui.QApplication.translate("MainWindow", "Mask", None, QtGui.QApplication.UnicodeUTF8))
        self.gbMoment.setTitle(QtGui.QApplication.translate("MainWindow", "Moment", None, QtGui.QApplication.UnicodeUTF8))
        self.rbMomentEnable.setText(QtGui.QApplication.translate("MainWindow", "Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMomentMin.setText(QtGui.QApplication.translate("MainWindow", "Area Min", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMomentMax.setText(QtGui.QApplication.translate("MainWindow", "Area Max", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageROI), QtGui.QApplication.translate("MainWindow", "ROI", None, QtGui.QApplication.UnicodeUTF8))
        self.gbColorMask.setTitle(QtGui.QApplication.translate("MainWindow", "Color Mask HSV", None, QtGui.QApplication.UnicodeUTF8))
        self.rbColorMask.setText(QtGui.QApplication.translate("MainWindow", "Binary/Mask", None, QtGui.QApplication.UnicodeUTF8))
        self.cbColorMask.setItemText(0, QtGui.QApplication.translate("MainWindow", "HSV", None, QtGui.QApplication.UnicodeUTF8))
        self.cbColorMask.setItemText(1, QtGui.QApplication.translate("MainWindow", "HSL", None, QtGui.QApplication.UnicodeUTF8))
        self.cbColorMask.setItemText(2, QtGui.QApplication.translate("MainWindow", "RGB", None, QtGui.QApplication.UnicodeUTF8))
        self.cbColorMask.setItemText(3, QtGui.QApplication.translate("MainWindow", "Lab", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCmask2_1.setText(QtGui.QApplication.translate("MainWindow", "Saturation", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCmask1_1.setText(QtGui.QApplication.translate("MainWindow", "Hue", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCmask3_1.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.gbGreyscale.setTitle(QtGui.QApplication.translate("MainWindow", "Greyscale conversions", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listGreyscale.isSortingEnabled()
        self.listGreyscale.setSortingEnabled(False)
        item = self.listGreyscale.item(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Greyscale", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "---Extract RGB plane---", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Red", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Green", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(7)
        item.setText(QtGui.QApplication.translate("MainWindow", "---Extract HSV/HSL---", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(8)
        item.setText(QtGui.QApplication.translate("MainWindow", "Hue", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(9)
        item.setText(QtGui.QApplication.translate("MainWindow", "Saturation", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(10)
        item.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(11)
        item.setText(QtGui.QApplication.translate("MainWindow", "Lightness", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(13)
        item.setText(QtGui.QApplication.translate("MainWindow", "---Extract CIELAB---", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(14)
        item.setText(QtGui.QApplication.translate("MainWindow", "L*", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(15)
        item.setText(QtGui.QApplication.translate("MainWindow", "a*", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listGreyscale.item(16)
        item.setText(QtGui.QApplication.translate("MainWindow", "b*", None, QtGui.QApplication.UnicodeUTF8))
        self.listGreyscale.setSortingEnabled(__sortingEnabled)
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageColorOps), QtGui.QApplication.translate("MainWindow", "Color Ops", None, QtGui.QApplication.UnicodeUTF8))
        self.gbThresholding.setTitle(QtGui.QApplication.translate("MainWindow", "Thresholding", None, QtGui.QApplication.UnicodeUTF8))
        self.btnThreshGlobal.setText(QtGui.QApplication.translate("MainWindow", "Global", None, QtGui.QApplication.UnicodeUTF8))
        self.btnThreshMean.setText(QtGui.QApplication.translate("MainWindow", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.btnThreshGaussian.setText(QtGui.QApplication.translate("MainWindow", "Gaussian", None, QtGui.QApplication.UnicodeUTF8))
        self.cbThreshType.setItemText(0, QtGui.QApplication.translate("MainWindow", "BINARY", None, QtGui.QApplication.UnicodeUTF8))
        self.cbThreshType.setItemText(1, QtGui.QApplication.translate("MainWindow", "BINARY_INV", None, QtGui.QApplication.UnicodeUTF8))
        self.cbThreshType.setItemText(2, QtGui.QApplication.translate("MainWindow", "TRUNC", None, QtGui.QApplication.UnicodeUTF8))
        self.cbThreshType.setItemText(3, QtGui.QApplication.translate("MainWindow", "TOZERO", None, QtGui.QApplication.UnicodeUTF8))
        self.cbThreshType.setItemText(4, QtGui.QApplication.translate("MainWindow", "TOZERO_INV", None, QtGui.QApplication.UnicodeUTF8))
        self.lblThreshMaxval.setText(QtGui.QApplication.translate("MainWindow", "maxval", None, QtGui.QApplication.UnicodeUTF8))
        self.lblThreshThresh.setText(QtGui.QApplication.translate("MainWindow", "thresh", None, QtGui.QApplication.UnicodeUTF8))
        self.gbHistograms.setTitle(QtGui.QApplication.translate("MainWindow", "Histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEqualizeHist.setText(QtGui.QApplication.translate("MainWindow", "Equalize", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCLAHE.setText(QtGui.QApplication.translate("MainWindow", "CLAHE", None, QtGui.QApplication.UnicodeUTF8))
        self.gbSmoothing.setTitle(QtGui.QApplication.translate("MainWindow", "Smoothing", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBlurMedian.setText(QtGui.QApplication.translate("MainWindow", "Median", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBlurAveraging.setText(QtGui.QApplication.translate("MainWindow", "Averaging", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBlurGaussian.setText(QtGui.QApplication.translate("MainWindow", "Gaussian", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFilterBilateral.setText(QtGui.QApplication.translate("MainWindow", "Bilateral", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageGreyscaleOps), QtGui.QApplication.translate("MainWindow", "Greyscale Ops", None, QtGui.QApplication.UnicodeUTF8))
        self.gbMorphology.setTitle(QtGui.QApplication.translate("MainWindow", "Morphology", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDilate.setText(QtGui.QApplication.translate("MainWindow", "Dilate", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMorphGradient.setText(QtGui.QApplication.translate("MainWindow", "Morph Gradient", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBlackHat.setText(QtGui.QApplication.translate("MainWindow", "Black Hat", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTopHat.setText(QtGui.QApplication.translate("MainWindow", "Top Hat", None, QtGui.QApplication.UnicodeUTF8))
        self.btnErode.setText(QtGui.QApplication.translate("MainWindow", "Erode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Kernel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageBinaryOps), QtGui.QApplication.translate("MainWindow", "Binary Ops", None, QtGui.QApplication.UnicodeUTF8))
        self.gbEdges.setTitle(QtGui.QApplication.translate("MainWindow", "Edge Detection", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSobelY.setText(QtGui.QApplication.translate("MainWindow", "Sobel Y", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCannyEdges.setText(QtGui.QApplication.translate("MainWindow", "Canny Edges", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSobelX.setText(QtGui.QApplication.translate("MainWindow", "Sobel X", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLaplacian.setText(QtGui.QApplication.translate("MainWindow", "Laplacian", None, QtGui.QApplication.UnicodeUTF8))
        self.gbFitShapes.setTitle(QtGui.QApplication.translate("MainWindow", "Fit Shapes", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFindMinCircle.setText(QtGui.QApplication.translate("MainWindow", "Min Circle", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFindRectangle.setText(QtGui.QApplication.translate("MainWindow", "Rectangle", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFindMinRectangle.setText(QtGui.QApplication.translate("MainWindow", "Min Rectangle", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFitEllipse.setText(QtGui.QApplication.translate("MainWindow", "Fit Ellipse", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageFindContours), QtGui.QApplication.translate("MainWindow", "Find Contours", None, QtGui.QApplication.UnicodeUTF8))
        self.gbTemplate.setTitle(QtGui.QApplication.translate("MainWindow", "Template Matching", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTemplateFind.setText(QtGui.QApplication.translate("MainWindow", "Match Template", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTemplateMethod.setItemText(0, QtGui.QApplication.translate("MainWindow", "SQDIFF", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTemplateMethod.setItemText(1, QtGui.QApplication.translate("MainWindow", "SQDIFF_NORMED", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTemplateMethod.setItemText(2, QtGui.QApplication.translate("MainWindow", "CCORR", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTemplateMethod.setItemText(3, QtGui.QApplication.translate("MainWindow", "CCORR_NORMED", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTemplateMethod.setItemText(4, QtGui.QApplication.translate("MainWindow", "CCOEFF", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTemplateMethod.setItemText(5, QtGui.QApplication.translate("MainWindow", "CCOEFF_NORMED", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageFeatureDetection), QtGui.QApplication.translate("MainWindow", "Feature Detection", None, QtGui.QApplication.UnicodeUTF8))
        self.btnApply.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCancel.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("MainWindow", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("MainWindow", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("MainWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Load Image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Image.setText(QtGui.QApplication.translate("MainWindow", "Save Image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOriginal_Image.setText(QtGui.QApplication.translate("MainWindow", "Original Image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActive_Image.setText(QtGui.QApplication.translate("MainWindow", "Active Image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_template.setText(QtGui.QApplication.translate("MainWindow", "Load template", None, QtGui.QApplication.UnicodeUTF8))

